### ISSUE TITLE
BlogCore.App issue

### ISSUE THREAD

**Issue by hitaspdotnet** [thangchung/blog-core#18]
Hi sir.
Thanks for amazing commenting and helpful details
If is possible I need some help at running BlogCore.App. I am student and I cant understand why got this errors:
`ERROR in [at-loader] ./ClientApp/containers/Blog/BlogForm.tsx:133:19 
    TS2322: Type '{ name: "moderateComments"; placeholder: "Moderate comments"; component: typeof Checkbox; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Field<GenericFieldHTMLAttributes>> & Readonly<{ c...'.
  Type '{ name: "moderateComments"; placeholder: "Moderate comments"; component: typeof Checkbox; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Field<GenericFieldHTMLAttributes>> & Readonly<{ ch...'.
    Type '{ name: "moderateComments"; placeholder: "Moderate comments"; component: typeof Checkbox; }' is not assignable to type 'Readonly<BaseFieldProps<GenericFieldHTMLAttributes> & TextareaHTMLAttributes<HTMLTextAreaElement>>'.
      Types of property 'component' are incompatible.
        Type 'typeof Checkbox' is not assignable to type '"input" | "select" | "textarea" | ComponentClass<(InputHTMLAttributes<HTMLInputElement> & Wrapped...'.
          Type 'typeof Checkbox' is not assignable to type 'StatelessComponent<(InputHTMLAttributes<HTMLInputElement> & WrappedFieldProps) | (SelectHTMLAttri...'.`
And 4 mores like this
in [at-loader] ./ClientApp/containers/Blog/BlogForm.tsx:133:19
&
in [at-loader] ./ClientApp/redux/modules/blog.ts:281:14 
&
in [at-loader] ./ClientApp/redux/modules/common.ts:20:14 
&
in [at-loader] ./node_modules/rxjs/scheduler/VirtualTimeScheduler.d.ts:22:22 

Thanks

**Comment by mjamro** [comment]
I'm seeing the same thing. Has anyone solved how to fix that?

**Comment by thangchung** [comment]
This is caused by the invalid version of `ts packages`, make sure that you guys used the correct one version of typescript

**Comment by mjamro** [comment]
@thangchung Soo... which version is valid?

**Comment by amit-sonora** [comment]
HI,
I am facing the same issue mentioned above. Anybody able to solve?

Thx
Amit

**Comment by amit-sonora** [comment]
Hi.. how to resolve this issue?
Thx
Amit

**Comment by BionStt** [comment]
@amit-sonora 
@mariuszjamro ,
@hitaspdotnet 
Hello brother,
to ix this issue. you just change knowaction to anyaction. please check in reducer.

in [at-loader] ./ClientApp/containers/Blog/BlogForm.tsx:133:19
&
in [at-loader] ./ClientApp/redux/modules/blog.ts:281:14
&
in [at-loader] ./ClientApp/redux/modules/common.ts:20:14

i use windows powershell.
in blog-core folder run dotnet restore
in blog-core/src/hosts/blogapp/ npn i node 
then npm install 
then npm i node-sass@4.5.3
then node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
then node node_modules/webpack/bin/webpack.js 

dotnet run


you can try

thank you

**Comment by amit-sonora** [comment]
Thx Bion,
But issue persist.

![image](https://user-images.githubusercontent.com/47025741/56913882-5dbe3880-6ad0-11e9-89f3-9f739ea0e710.png)

**Comment by BionStt** [comment]
export const reducer: Reducer<CommonState> = (
  state: CommonState,
  action: KnownAction
) => {

blog-core/src/Hosts/BlogCore.App/ClientApp/redux/modules/Common.ts
blog-core/src/Hosts/BlogCore.App/ClientApp/redux/modules/Blog.ts

knowaction to anyaction

**Comment by BionStt** [comment]
@amit-sonora

**Comment by BionStt** [comment]
in blogmanagement change number to any
blog-core/src/Hosts/BlogCore.App/ClientApp/containers/Blog/BlogManagement.tsx

type BlogProps = BlogStore.BlogState &
  typeof BlogStore.actionCreators &
  RouteComponentProps<{ page: number }>;

@amit-sonora

**Comment by amit-sonora** [comment]
Thx Bien.. can you please post compete changed files ..
Sorry but I am a beginner in js.

**Comment by BionStt** [comment]
![test1](https://user-images.githubusercontent.com/43228630/56939660-cdb1da80-6b33-11e9-8186-cc6896ff51ba.jpg)

**Comment by BionStt** [comment]
![test2](https://user-images.githubusercontent.com/43228630/56939671-dbfff680-6b33-11e9-8617-ff023265b14b.jpg)

**Comment by BionStt** [comment]
https://github.com/sass/node-sass/releases

if you need node-sass win32-x64-67. 
@amit-sonora

**Comment by amit-sonora** [comment]
THx a ton Bion.
Able to see at least below screen.

![image](https://user-images.githubusercontent.com/47025741/56941359-a35f1d80-6b31-11e9-938c-4e613a89e674.png)
